#!/usr/bin/env python3
"""
AI Operating System — Setup Wizard

Run this after cloning the template to configure your business AI OS.
Creates .env, setup_config.yaml, .claude/settings.local.json, and initializes databases.

Usage: python3 setup.py
"""

import json
import os
import shutil
import sqlite3
import sys
from datetime import datetime
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent


def banner():
    print()
    print("=" * 55)
    print("  AI Operating System — Setup Wizard")
    print("=" * 55)
    print()


def ask(prompt, default=None, required=True, secret=False):
    """Prompt user for input with optional default."""
    suffix = f" [{default}]" if default else ""
    while True:
        if secret:
            import getpass
            val = getpass.getpass(f"  {prompt}{suffix}: ").strip()
        else:
            val = input(f"  {prompt}{suffix}: ").strip()
        if not val and default:
            return default
        if not val and not required:
            return ""
        if not val and required:
            print("    Required. Please enter a value.")
            continue
        # Basic input validation — strip control chars, limit length
        val = val.replace("\x00", "")[:500]
        return val


def ask_choice(prompt, options):
    """Prompt user to pick from a list."""
    print(f"  {prompt}")
    for i, opt in enumerate(options, 1):
        print(f"    {i}. {opt}")
    while True:
        val = input(f"  Choice [1-{len(options)}]: ").strip()
        try:
            idx = int(val) - 1
            if 0 <= idx < len(options):
                return options[idx]
        except ValueError:
            pass
        print(f"    Please enter a number 1-{len(options)}")


def detect_python():
    """Find Python 3.11+ path."""
    candidates = [
        shutil.which("python3.11"),
        shutil.which("python3.12"),
        shutil.which("python3.13"),
        "/opt/homebrew/opt/python@3.11/bin/python3.11",
        "/opt/homebrew/opt/python@3.12/bin/python3.12",
        "/usr/local/bin/python3.11",
        "/usr/local/bin/python3.12",
        shutil.which("python3"),
    ]
    for c in candidates:
        if c and os.path.exists(c):
            return c
    return shutil.which("python3") or "python3"


def detect_claude():
    """Find Claude CLI path."""
    candidates = [
        shutil.which("claude"),
        "/opt/homebrew/bin/claude",
        "/usr/local/bin/claude",
    ]
    for c in candidates:
        if c and os.path.exists(c):
            return c
    return "claude"


def check_ollama():
    """Check if Ollama is available."""
    try:
        import requests
        r = requests.get("http://localhost:11434/api/tags", timeout=3)
        return r.status_code == 200
    except Exception:
        return False


def create_env(config):
    """Generate .env from template values."""
    env_path = PROJECT_ROOT / ".env"
    lines = [
        "# AI Operating System — Environment Variables",
        f"# Generated by setup.py on {datetime.now().strftime('%Y-%m-%d %H:%M')}",
        "",
        f"ANTHROPIC_API_KEY={config.get('anthropic_key', '')}",
        f"OPENAI_API_KEY={config.get('openai_key', '')}",
        f"PINECONE_API_KEY={config.get('pinecone_key', '')}",
        f"TELEGRAM_BOT_TOKEN={config.get('telegram_token', '')}",
        f"TELEGRAM_ALLOWED_USERS={config.get('telegram_user_id', '')}",
    ]
    env_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    os.chmod(str(env_path), 0o600)  # Owner read/write only — no group/other access
    print(f"  Created: {env_path} (permissions: 600)")


def create_setup_config(config):
    """Generate setup_config.yaml."""
    import yaml
    cfg_path = PROJECT_ROOT / "setup_config.yaml"
    cfg_path.write_text(yaml.dump(config, default_flow_style=False), encoding="utf-8")
    os.chmod(str(cfg_path), 0o600)  # Owner read/write only
    print(f"  Created: {cfg_path} (permissions: 600)")


def create_settings_local(config):
    """Generate .claude/settings.local.json with correct paths."""
    python_path = config["python_path"]
    project_path = str(PROJECT_ROOT)

    settings = {
        "permissions": {
            "allow": [
                "Bash(git status:*)",
                "Bash(git diff:*)",
                "Bash(git log:*)",
                "Bash(git add:*)",
                "Bash(git commit:*)",
                "Bash(git push:*)",
                f"Bash({python_path} tools/*)",
                f"Bash({python_path} .claude/skills/*/scripts/*)",
                "Bash(wc:*)",
                "Bash(ls:*)",
                "Bash(mkdir:*)",
                "Bash(date:*)",
                "Bash(pip3 install -r requirements.txt)",
                f"Read(//{project_path}/**)",
            ]
        },
        "hooks": {
            "PreToolUse": [
                {
                    "matcher": "Bash",
                    "hooks": [
                        {
                            "type": "command",
                            "command": f"{python_path} .claude/hooks/pre_tool_guard.py",
                            "timeout": 5,
                        }
                    ]
                }
            ],
            "PostToolUse": [
                {
                    "matcher": "Bash",
                    "hooks": [
                        {
                            "type": "command",
                            "command": f"{python_path} .claude/hooks/validate_output.py",
                            "timeout": 5,
                        }
                    ]
                }
            ],
            "Stop": [
                {
                    "hooks": [
                        {
                            "type": "command",
                            "command": f"{python_path} .claude/skills/memory/scripts/auto_capture.py",
                            "timeout": 60,
                            "async": True,
                        }
                    ]
                }
            ],
        },
    }

    settings_path = PROJECT_ROOT / ".claude" / "settings.local.json"
    settings_path.write_text(
        json.dumps(settings, indent=2) + "\n", encoding="utf-8"
    )
    print(f"  Created: {settings_path}")


def create_plist(config):
    """Generate launchd plist for Telegram bot daemon."""
    project_path = str(PROJECT_ROOT)
    python_path = config["python_path"]
    agent_name = config["agent_name"].lower().replace(" ", "-")
    label = f"com.aios.{agent_name}-bot"

    plist = f"""<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>{label}</string>
    <key>ProgramArguments</key>
    <array>
        <string>{python_path}</string>
        <string>{project_path}/tools/telegram/bot_polling.py</string>
    </array>
    <key>WorkingDirectory</key>
    <string>{project_path}</string>
    <key>EnvironmentVariables</key>
    <dict>
        <key>PYTHONPATH</key>
        <string>{project_path}</string>
    </dict>
    <key>RunAtLoad</key>
    <true/>
    <key>KeepAlive</key>
    <true/>
    <key>StandardOutPath</key>
    <string>{project_path}/data/bot_stdout.log</string>
    <key>StandardErrorPath</key>
    <string>{project_path}/data/bot_stderr.log</string>
</dict>
</plist>"""

    plist_path = PROJECT_ROOT / "tools" / "telegram" / f"{agent_name}-bot.plist"
    plist_path.parent.mkdir(parents=True, exist_ok=True)
    plist_path.write_text(plist, encoding="utf-8")
    print(f"  Created: {plist_path}")


def init_databases(config):
    """Initialize SQLite databases with schema."""
    data_dir = PROJECT_ROOT / "data"
    data_dir.mkdir(exist_ok=True)

    # activity.db — tasks, events, messages
    conn = sqlite3.connect(str(data_dir / "activity.db"))
    conn.executescript("""
        CREATE TABLE IF NOT EXISTS tasks (
            id TEXT PRIMARY KEY,
            source TEXT,
            request TEXT,
            status TEXT DEFAULT 'pending',
            department TEXT DEFAULT 'general',
            created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
            completed_at DATETIME,
            summary TEXT
        );

        CREATE TABLE IF NOT EXISTS telegram_events (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            message_id TEXT UNIQUE,
            user_id TEXT NOT NULL,
            chat_id TEXT NOT NULL,
            message_text TEXT,
            intent TEXT,
            handler TEXT,
            response TEXT,
            department TEXT DEFAULT 'general',
            created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
            processing_time_ms INTEGER
        );

        CREATE TABLE IF NOT EXISTS messages (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            user_id TEXT NOT NULL,
            platform TEXT DEFAULT 'telegram',
            direction TEXT NOT NULL,
            content TEXT NOT NULL,
            intent TEXT,
            department TEXT DEFAULT 'general',
            metadata TEXT,
            created_at DATETIME DEFAULT CURRENT_TIMESTAMP
        );

        CREATE INDEX IF NOT EXISTS idx_messages_user_date
            ON messages(user_id, created_at DESC);
        CREATE INDEX IF NOT EXISTS idx_messages_department
            ON messages(department);
        CREATE INDEX IF NOT EXISTS idx_tasks_department
            ON tasks(department);
    """)
    conn.close()
    print("  Initialized: data/activity.db")

    # memory.db — local typed memory
    conn = sqlite3.connect(str(data_dir / "memory.db"))
    conn.executescript("""
        CREATE TABLE IF NOT EXISTS memory_entries (
            id INTEGER PRIMARY KEY,
            content TEXT NOT NULL,
            entry_type TEXT DEFAULT 'fact',
            importance INTEGER DEFAULT 5,
            created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
            source TEXT DEFAULT 'manual',
            embedding BLOB,
            embedding_model TEXT,
            updated_at DATETIME
        );
    """)
    conn.close()
    print("  Initialized: data/memory.db")


def create_memory_md(config):
    """Create initial MEMORY.md."""
    business_name = config["business_name"]
    agent_name = config["agent_name"]
    today = datetime.now().strftime("%Y-%m-%d")

    content = f"""# Persistent Memory — {business_name}

> This file contains curated long-term facts that persist across sessions.
> The AI ({agent_name}) reads this at the start of each session.

## Business Identity

- **Business**: {business_name}
- **Agent**: {agent_name}
- **Type**: {config.get('business_type', 'small')}
- **Setup date**: {today}

## User Preferences

- (Add your preferences here)

## Key Facts

- (Add key facts about your business)

## Active Projects

- (List current projects)

## Learned Behaviors

- Always check tools/manifest.md before creating new scripts
- Follow GOTCHA framework: Goals, Orchestration, Tools, Context, Hardprompts, Args

---
*Last updated: {today}*
"""
    mem_path = PROJECT_ROOT / "memory" / "MEMORY.md"
    mem_path.write_text(content, encoding="utf-8")
    print(f"  Created: {mem_path}")


def create_daily_log():
    """Create today's daily log."""
    today = datetime.now()
    log_path = PROJECT_ROOT / "memory" / "logs" / f"{today.strftime('%Y-%m-%d')}.md"
    content = f"""# Daily Log: {today.strftime('%Y-%m-%d')}

> Session log for {today.strftime('%A, %B %d, %Y')}

---

## Events & Notes

- {today.strftime('%H:%M')} [event] AI Operating System initialized via setup wizard
"""
    log_path.write_text(content, encoding="utf-8")
    print(f"  Created: {log_path}")


def verify(config):
    """Run verification checks."""
    print("\n  Verification:")
    checks = [
        (".env exists", (PROJECT_ROOT / ".env").exists()),
        ("setup_config.yaml exists", (PROJECT_ROOT / "setup_config.yaml").exists()),
        ("settings.local.json exists", (PROJECT_ROOT / ".claude" / "settings.local.json").exists()),
        ("activity.db exists", (PROJECT_ROOT / "data" / "activity.db").exists()),
        ("memory.db exists", (PROJECT_ROOT / "data" / "memory.db").exists()),
        ("MEMORY.md exists", (PROJECT_ROOT / "memory" / "MEMORY.md").exists()),
    ]
    all_pass = True
    for label, passed in checks:
        status = "OK" if passed else "FAIL"
        print(f"    [{status}] {label}")
        if not passed:
            all_pass = False
    return all_pass


def main():
    banner()

    # --- Business Configuration ---
    print("Business Configuration:")
    business_name = ask("Business name")
    agent_name = ask("Agent name (the AI's identity)", default="Atlas")
    business_type = ask_choice(
        "Business type:",
        ["solo", "small", "mid-market", "enterprise"]
    )

    # --- User Configuration ---
    print("\nUser Configuration:")
    user_name = ask("Your name")
    user_email = ask("Email", required=False)
    telegram_user_id = ask("Telegram user ID (or 'skip')", required=False)
    if telegram_user_id.lower() == "skip":
        telegram_user_id = ""

    # --- Memory Configuration ---
    print("\nMemory Configuration:")
    mem0_user_id = ask("User ID for mem0", default=user_name.lower().split()[0])
    pinecone_index = ask(
        "Pinecone index name (or 'skip' for local-only)",
        default=f"{business_name.lower().replace(' ', '-')}-memory"
    )
    if pinecone_index.lower() == "skip":
        pinecone_index = ""

    # --- Environment Detection ---
    print("\nEnvironment Detection:")
    python_path = detect_python()
    print(f"  Python: {python_path}")
    claude_path = detect_claude()
    print(f"  Claude CLI: {claude_path}")
    ollama_available = check_ollama()
    print(f"  Ollama: {'available' if ollama_available else 'not detected'}")

    # --- API Keys ---
    print("\nAPI Keys (stored in .env — leave blank to skip):")
    anthropic_key = ask("ANTHROPIC_API_KEY", required=False, secret=True)
    openai_key = ask("OPENAI_API_KEY (for mem0)", required=False, secret=True)
    pinecone_key = ask("PINECONE_API_KEY", required=False, secret=True) if pinecone_index else ""
    telegram_token = ask("TELEGRAM_BOT_TOKEN", required=False, secret=True) if telegram_user_id else ""

    # --- Build config ---
    config = {
        "business_name": business_name,
        "agent_name": agent_name,
        "business_type": business_type,
        "user_name": user_name,
        "user_email": user_email,
        "telegram_user_id": telegram_user_id,
        "mem0_user_id": mem0_user_id,
        "pinecone_index": pinecone_index,
        "python_path": python_path,
        "claude_path": claude_path,
        "ollama_available": ollama_available,
        "anthropic_key": anthropic_key,
        "openai_key": openai_key,
        "pinecone_key": pinecone_key,
        "telegram_token": telegram_token,
        "setup_date": datetime.now().strftime("%Y-%m-%d"),
    }

    # --- Generate files ---
    print("\n" + "=" * 55)
    print("  Generating configuration files...")
    print("=" * 55 + "\n")

    create_env(config)
    create_setup_config(config)
    create_settings_local(config)
    if telegram_user_id:
        create_plist(config)
    init_databases(config)
    create_memory_md(config)
    create_daily_log()

    # --- Verify ---
    all_pass = verify(config)

    print("\n" + "=" * 55)
    if all_pass:
        print(f"  Setup complete! {agent_name} is ready.")
        print(f"  Business: {business_name}")
        print(f"  Type: {business_type}")
    else:
        print("  Setup completed with warnings — check failed items above.")

    print()
    print("  Next steps:")
    print("    1. Review .env and add any missing API keys")
    print("    2. Run: pip install -r requirements.txt")
    print("    3. Open this directory in Claude Code")
    print("    4. Fill in client_onboarding/ documents")
    print("    5. Start building skills!")
    print("=" * 55)
    print()


if __name__ == "__main__":
    main()
